// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "wmb-rest-api/model/entity"

	mock "github.com/stretchr/testify/mock"
)

// AuthRepositoryInterface is an autogenerated mock type for the AuthRepositoryInterface type
type AuthRepositoryInterface struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: uc
func (_m *AuthRepositoryInterface) CreateUser(uc *entity.UserCredential) error {
	ret := _m.Called(uc)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.UserCredential) error); ok {
		r0 = rf(uc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindUser provides a mock function with given fields: uc
func (_m *AuthRepositoryInterface) FindUser(uc *entity.UserCredential) error {
	ret := _m.Called(uc)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.UserCredential) error); ok {
		r0 = rf(uc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAuthRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthRepositoryInterface creates a new instance of AuthRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthRepositoryInterface(t mockConstructorTestingTNewAuthRepositoryInterface) *AuthRepositoryInterface {
	mock := &AuthRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
