// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LopeiRepositoryInterface is an autogenerated mock type for the LopeiRepositoryInterface type
type LopeiRepositoryInterface struct {
	mock.Mock
}

// CheckBalance provides a mock function with given fields: phoneNumber
func (_m *LopeiRepositoryInterface) CheckBalance(phoneNumber string) (float64, error) {
	ret := _m.Called(phoneNumber)

	var r0 float64
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(phoneNumber)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(phoneNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DoPayment provides a mock function with given fields: phoneNumber, amount
func (_m *LopeiRepositoryInterface) DoPayment(phoneNumber string, amount float64) error {
	ret := _m.Called(phoneNumber, amount)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64) error); ok {
		r0 = rf(phoneNumber, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewLopeiRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewLopeiRepositoryInterface creates a new instance of LopeiRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLopeiRepositoryInterface(t mockConstructorTestingTNewLopeiRepositoryInterface) *LopeiRepositoryInterface {
	mock := &LopeiRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
