// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "wmb-rest-api/model/entity"

	mock "github.com/stretchr/testify/mock"
)

// TableRepositoryInterface is an autogenerated mock type for the TableRepositoryInterface type
type TableRepositoryInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: t
func (_m *TableRepositoryInterface) Create(t *entity.Table) error {
	ret := _m.Called(t)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Table) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: t
func (_m *TableRepositoryInterface) Delete(t *entity.Table) error {
	ret := _m.Called(t)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Table) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: by
func (_m *TableRepositoryInterface) FindAll(by map[string]interface{}) ([]entity.Table, error) {
	ret := _m.Called(by)

	var r0 []entity.Table
	if rf, ok := ret.Get(0).(func(map[string]interface{}) []entity.Table); ok {
		r0 = rf(by)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Table)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[string]interface{}) error); ok {
		r1 = rf(by)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: t
func (_m *TableRepositoryInterface) FindById(t *entity.Table) error {
	ret := _m.Called(t)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Table) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: t
func (_m *TableRepositoryInterface) Update(t *entity.Table) error {
	ret := _m.Called(t)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Table) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTableRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewTableRepositoryInterface creates a new instance of TableRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTableRepositoryInterface(t mockConstructorTestingTNewTableRepositoryInterface) *TableRepositoryInterface {
	mock := &TableRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
