// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "wmb-rest-api/model/entity"

	mock "github.com/stretchr/testify/mock"
)

// AuthUseCaseInterface is an autogenerated mock type for the AuthUseCaseInterface type
type AuthUseCaseInterface struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: uc
func (_m *AuthUseCaseInterface) CreateUser(uc *entity.UserCredential) error {
	ret := _m.Called(uc)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.UserCredential) error); ok {
		r0 = rf(uc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindUser provides a mock function with given fields: uc
func (_m *AuthUseCaseInterface) FindUser(uc *entity.UserCredential) error {
	ret := _m.Called(uc)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.UserCredential) error); ok {
		r0 = rf(uc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAuthUseCaseInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthUseCaseInterface creates a new instance of AuthUseCaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthUseCaseInterface(t mockConstructorTestingTNewAuthUseCaseInterface) *AuthUseCaseInterface {
	mock := &AuthUseCaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
